version: '3'

services:
  parachute:
    image: imperialsys/parachute-ending-api
    restart: unless-stopped
    container_name: parachute-ending-api
    volumes:
      - ./:/app/
    ports:
      - "8090:5000"

networks:
  default:
    external:
      name: silico-reborn_default









